config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles

end

app/models/article.rb
require "net/http"
require "uri"
class Article < ActiveRecord::Base
  acts_as_paranoid
  has_many :comments
 
  after_save :after_save
  def after_save
    puts "Saved"
  end

  after_create :after_create
  def after_create
    if ENV["REST_SYNC_REALTIME"] === '' then 
      return
    end
    uri = URI.parse( ENV["REST_SYNC_ROOT"] )
    http = Net::HTTP.new( uri.host, uri.port)
    remoteNewUrl = "/rest-sync/articles"

    request = Net::HTTP::Post.new(remoteNewUrl)
    request.set_form_data( attributes )
    http.request(request)  
  end
 
  after_update :after_update
  after_destroy :after_update
  def after_update
    if ENV["REST_SYNC_REALTIME"] === '' then 
      return
    end
    uri = URI.parse( ENV["REST_SYNC_ROOT"] )
    http = Net::HTTP.new( uri.host, uri.port)
    remoteUpdateUrl = "/rest-sync/articles/" + attributes["id"].to_s

    request = Net::HTTP::Put.new(remoteUpdateUrl)
    request.set_form_data( attributes )
    http.request(request)  
  end
end

app/models/comment.rb
require "net/http"
require "uri"

class Comment < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :article
  
  after_create :after_create

  def after_create
    if ENV["REST_SYNC_REALTIME"] === '' then 
      return
    end
    uri = URI.parse( ENV["REST_SYNC_ROOT"] )
    http = Net::HTTP.new( uri.host, uri.port)
    remoteNewUrl = "/rest-sync/comments"

    request = Net::HTTP::Post.new(remoteNewUrl)
    request.set_form_data( attributes )
    http.request(request)  
  end
 
  after_update :after_update
  after_destroy :after_update
  def after_update
    if ENV["REST_SYNC_REALTIME"] === '' then 
      return
    end
    uri = URI.parse( ENV["REST_SYNC_ROOT"] )
    http = Net::HTTP.new( uri.host, uri.port)
    puts "UPDATING"
    puts attributes
    remoteUpdateUrl = "/rest-sync/comments/" + attributes["id"].to_s

    request = Net::HTTP::Put.new(remoteUpdateUrl)
    request.set_form_data( attributes )
    http.request(request)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /articles
  # GET /articles.json
  def index  
    @articles = Article.all
    if params["updated_since"] then
      articles = Article.unscoped.where('updated_at > ?',params["updated_since"].to_datetime)
    else
      if params["external_id"] then
        articles = Article.unscoped.where('external_id = ?', params["external_id"])
      else
        articles = Article.unscoped
      end
    end

    respond_to do |format|
      format.html
      format.json {render json: articles}
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new( article_params )

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    puts article_params
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :deleted_at, :updated_at, :external_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    if params["updated_since"] then
      comments = Comment.unscoped.where('updated_at > ?',params["updated_since"].to_datetime)
    else
      if params["external_id"] then
        comments = Comment.unscoped.where('external_id = ?', params["external_id"])
      else
        comments = Comment.unscoped
      end
    end

    respond_to do |format|
      format.html
      format.json {render json: comments}
    end
      # @comments = Comment.unscoped
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :body, :deleted_at, :updated_at, :external_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Deleted At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.author %></td>
        <td><%= article.deleted_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>External Id:</strong>
  <%= @article.external_id %>
</p>

<p>
  <strong>Updated At:</strong>
  <%= @article.updated_at %>
</p>

<p>
  <strong>Deleted At:</strong>
  <%= @article.deleted_at %>
</p>

<strong>Comments:</strong>
  <% @article.comments.each do |comment| %>
    <p><%= comment.body %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Body</th>
      <th>External Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= comment.external_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeteorSync</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>